/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class helloJni */

#ifndef _Included_helloJni
#define _Included_helloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     helloJni
 * Method:    displayHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_helloJni_displayHelloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
